"""업적 정의 및 체크 로직"""

ACHIEVEMENT_DEFINITIONS = [
    # === 연속 출근 (streak) ===
    {
        "code": "streak_3",
        "name": "출근 루키",
        "description": "3일 연속 출근 성공",
        "icon": "🌱",
        "category": "streak",
        "condition_type": "streak_days",
        "condition_value": 3,
        "reward_exp": 100,
        "reward_title": None,
    },
    {
        "code": "streak_7",
        "name": "일주일 전사",
        "description": "7일 연속 출근 성공",
        "icon": "🔥",
        "category": "streak",
        "condition_type": "streak_days",
        "condition_value": 7,
        "reward_exp": 300,
        "reward_title": "불꽃 출근러",
    },
    {
        "code": "streak_30",
        "name": "한달의 기적",
        "description": "30일 연속 출근 성공",
        "icon": "💎",
        "category": "streak",
        "condition_type": "streak_days",
        "condition_value": 30,
        "reward_exp": 1500,
        "reward_title": "철의 의지",
    },
    {
        "code": "streak_100",
        "name": "시간의 지배자",
        "description": "100일 연속 출근 성공",
        "icon": "👑",
        "category": "streak",
        "condition_type": "streak_days",
        "condition_value": 100,
        "reward_exp": 10000,
        "reward_title": "시간의 지배자",
    },
    {
        "code": "streak_365",
        "name": "전설의 직장인",
        "description": "365일 연속 출근 성공",
        "icon": "🏆",
        "category": "streak",
        "condition_type": "streak_days",
        "condition_value": 365,
        "reward_exp": 50000,
        "reward_title": "전설의 직장인",
    },
    # === 보스 클리어 (boss) ===
    {
        "code": "boss_1",
        "name": "첫 정시 출근",
        "description": "보스를 처음으로 클리어",
        "icon": "⚔️",
        "category": "boss",
        "condition_type": "boss_clears",
        "condition_value": 1,
        "reward_exp": 50,
        "reward_title": None,
    },
    {
        "code": "boss_10",
        "name": "보스 헌터",
        "description": "보스 10회 클리어",
        "icon": "🗡️",
        "category": "boss",
        "condition_type": "boss_clears",
        "condition_value": 10,
        "reward_exp": 500,
        "reward_title": "보스 헌터",
    },
    {
        "code": "boss_50",
        "name": "정시의 달인",
        "description": "보스 50회 클리어",
        "icon": "⏰",
        "category": "boss",
        "condition_type": "boss_clears",
        "condition_value": 50,
        "reward_exp": 3000,
        "reward_title": "정시의 달인",
    },
    {
        "code": "boss_100",
        "name": "무결점 출근",
        "description": "보스 100회 클리어",
        "icon": "🎯",
        "category": "boss",
        "condition_type": "boss_clears",
        "condition_value": 100,
        "reward_exp": 10000,
        "reward_title": "무결점 출근",
    },
    # === 총 출퇴근 (commute) ===
    {
        "code": "commute_1",
        "name": "모험의 시작",
        "description": "첫 출퇴근 완료",
        "icon": "🚶",
        "category": "commute",
        "condition_type": "total_commutes",
        "condition_value": 1,
        "reward_exp": 30,
        "reward_title": None,
    },
    {
        "code": "commute_50",
        "name": "베테랑 통근자",
        "description": "50회 출퇴근 완료",
        "icon": "🚇",
        "category": "commute",
        "condition_type": "total_commutes",
        "condition_value": 50,
        "reward_exp": 2000,
        "reward_title": "베테랑 통근자",
    },
    {
        "code": "commute_200",
        "name": "철도왕",
        "description": "200회 출퇴근 완료",
        "icon": "🚄",
        "category": "commute",
        "condition_type": "total_commutes",
        "condition_value": 200,
        "reward_exp": 8000,
        "reward_title": "철도왕",
    },
    # === 레벨 (level) ===
    {
        "code": "level_10",
        "name": "성장하는 직장인",
        "description": "레벨 10 달성",
        "icon": "📈",
        "category": "level",
        "condition_type": "level",
        "condition_value": 10,
        "reward_exp": 500,
        "reward_title": None,
    },
    {
        "code": "level_50",
        "name": "중견 용사",
        "description": "레벨 50 달성",
        "icon": "⭐",
        "category": "level",
        "condition_type": "level",
        "condition_value": 50,
        "reward_exp": 5000,
        "reward_title": "중견 용사",
    },
    {
        "code": "level_100",
        "name": "만렙 도전자",
        "description": "레벨 100 달성",
        "icon": "💫",
        "category": "level",
        "condition_type": "level",
        "condition_value": 100,
        "reward_exp": 20000,
        "reward_title": "만렙 도전자",
    },
    # === 특수 업적 (special) ===
    {
        "code": "monday_5",
        "name": "월요병 면역",
        "description": "월요일 5회 연속 정시 출근",
        "icon": "💪",
        "category": "special",
        "condition_type": "monday_boss_clears",
        "condition_value": 5,
        "reward_exp": 1000,
        "reward_title": "월요병 면역",
    },
    {
        "code": "hell_dungeon_10",
        "name": "지옥철 서바이버",
        "description": "2호선 던전 10회 클리어",
        "icon": "🔴",
        "category": "special",
        "condition_type": "hell_clears",
        "condition_value": 10,
        "reward_exp": 2000,
        "reward_title": "지옥철 서바이버",
    },
    {
        "code": "early_bird_5",
        "name": "얼리버드",
        "description": "목표 시간보다 10분 이상 일찍 도착 5회",
        "icon": "🐦",
        "category": "special",
        "condition_type": "early_arrivals",
        "condition_value": 5,
        "reward_exp": 800,
        "reward_title": "얼리버드",
    },
    {
        "code": "weekend_warrior",
        "name": "주말 전사",
        "description": "주말 출근 5회",
        "icon": "😤",
        "category": "special",
        "condition_type": "weekend_commutes",
        "condition_value": 5,
        "reward_exp": 1500,
        "reward_title": "주말 전사",
        "is_hidden": True,
    },
]
