"""장비 정의 데이터"""

EQUIPMENT_DEFINITIONS = [
    # === 머리 (head) ===
    {
        "code": "cap_basic",
        "name": "기본 볼캡",
        "description": "출퇴근 필수템. 헝클어진 머리를 가려준다.",
        "icon": "🧢",
        "slot": "head",
        "rarity": "common",
        "hp_bonus": 0,
        "mp_bonus": 5,
        "speed_bonus": 0,
        "luck_bonus": 2,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 100,
    },
    {
        "code": "noise_cancel_headphone",
        "name": "노이즈캔슬링 헤드폰",
        "description": "지옥철 소음을 완벽 차단. 인내력 대폭 상승.",
        "icon": "🎧",
        "slot": "head",
        "rarity": "rare",
        "hp_bonus": 0,
        "mp_bonus": 20,
        "speed_bonus": 0,
        "luck_bonus": 0,
        "exp_multiplier": 1.1,
        "unlock_condition": "hell_dungeon_10",
        "price": 2000,
    },
    {
        "code": "sleep_mask",
        "name": "수면 안대",
        "description": "서서 자는 기술을 터득. HP 회복 가능.",
        "icon": "😴",
        "slot": "head",
        "rarity": "uncommon",
        "hp_bonus": 15,
        "mp_bonus": 0,
        "speed_bonus": -5,
        "luck_bonus": 0,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 500,
    },
    {
        "code": "crown_legend",
        "name": "전설의 왕관",
        "description": "365일 연속 출근자에게만 주어지는 전설 장비.",
        "icon": "👑",
        "slot": "head",
        "rarity": "legendary",
        "hp_bonus": 30,
        "mp_bonus": 30,
        "speed_bonus": 10,
        "luck_bonus": 20,
        "exp_multiplier": 1.5,
        "unlock_condition": "streak_365",
        "price": 0,
    },
    # === 몸통 (body) ===
    {
        "code": "padded_jacket",
        "name": "롱패딩",
        "description": "겨울 출퇴근의 생존 필수품. 방어력 극대화.",
        "icon": "🧥",
        "slot": "body",
        "rarity": "common",
        "hp_bonus": 20,
        "mp_bonus": 0,
        "speed_bonus": -3,
        "luck_bonus": 0,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 300,
    },
    {
        "code": "suit_armor",
        "name": "정장 아머",
        "description": "면접날 착용하면 럭 보너스. 직장인의 갑옷.",
        "icon": "🤵",
        "slot": "body",
        "rarity": "uncommon",
        "hp_bonus": 10,
        "mp_bonus": 10,
        "speed_bonus": 0,
        "luck_bonus": 15,
        "exp_multiplier": 1.05,
        "unlock_condition": None,
        "price": 800,
    },
    {
        "code": "windbreaker",
        "name": "바람막이",
        "description": "가볍고 빠르다. 스피드 특화.",
        "icon": "🧤",
        "slot": "body",
        "rarity": "uncommon",
        "hp_bonus": 5,
        "mp_bonus": 0,
        "speed_bonus": 15,
        "luck_bonus": 0,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 600,
    },
    {
        "code": "invisible_cloak",
        "name": "투명 망토",
        "description": "지하철에서 빈자리를 발견하는 확률 증가.",
        "icon": "🫥",
        "slot": "body",
        "rarity": "epic",
        "hp_bonus": 10,
        "mp_bonus": 10,
        "speed_bonus": 5,
        "luck_bonus": 30,
        "exp_multiplier": 1.2,
        "unlock_condition": "level_50",
        "price": 5000,
    },
    # === 액세서리 (accessory) ===
    {
        "code": "tumbler",
        "name": "텀블러",
        "description": "따뜻한 커피 한 모금. HP를 회복시킨다.",
        "icon": "☕",
        "slot": "accessory",
        "rarity": "common",
        "hp_bonus": 10,
        "mp_bonus": 5,
        "speed_bonus": 0,
        "luck_bonus": 0,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 150,
    },
    {
        "code": "power_bank",
        "name": "보조배터리",
        "description": "폰이 죽으면 모험도 끝. MP 회복 필수템.",
        "icon": "🔋",
        "slot": "accessory",
        "rarity": "common",
        "hp_bonus": 0,
        "mp_bonus": 15,
        "speed_bonus": 0,
        "luck_bonus": 0,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 200,
    },
    {
        "code": "earbuds_pro",
        "name": "무선 이어버드 프로",
        "description": "팟캐스트 들으며 경험치 추가 획득.",
        "icon": "🎵",
        "slot": "accessory",
        "rarity": "rare",
        "hp_bonus": 0,
        "mp_bonus": 10,
        "speed_bonus": 0,
        "luck_bonus": 5,
        "exp_multiplier": 1.15,
        "unlock_condition": "commute_50",
        "price": 1500,
    },
    {
        "code": "lucky_charm",
        "name": "행운의 부적",
        "description": "환승 성공률 증가. 럭 대폭 상승.",
        "icon": "🍀",
        "slot": "accessory",
        "rarity": "rare",
        "hp_bonus": 0,
        "mp_bonus": 0,
        "speed_bonus": 0,
        "luck_bonus": 25,
        "exp_multiplier": 1.1,
        "unlock_condition": None,
        "price": 1800,
    },
    {
        "code": "smartwatch",
        "name": "스마트워치",
        "description": "실시간 도착 예정 알림. 지각 방지.",
        "icon": "⌚",
        "slot": "accessory",
        "rarity": "epic",
        "hp_bonus": 5,
        "mp_bonus": 5,
        "speed_bonus": 20,
        "luck_bonus": 10,
        "exp_multiplier": 1.2,
        "unlock_condition": "boss_50",
        "price": 3500,
    },
    # === 소모품 (consumable) ===
    {
        "code": "energy_drink",
        "name": "에너지 드링크",
        "description": "즉시 스피드 +30. 1회용.",
        "icon": "⚡",
        "slot": "consumable",
        "rarity": "common",
        "hp_bonus": 0,
        "mp_bonus": 0,
        "speed_bonus": 30,
        "luck_bonus": 0,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 50,
    },
    {
        "code": "hp_potion",
        "name": "비타민 젤리",
        "description": "HP를 30 회복시킨다. 지각 페널티 복구용.",
        "icon": "💊",
        "slot": "consumable",
        "rarity": "common",
        "hp_bonus": 30,
        "mp_bonus": 0,
        "speed_bonus": 0,
        "luck_bonus": 0,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 80,
    },
    {
        "code": "exp_booster",
        "name": "경험치 부스터",
        "description": "다음 출퇴근 경험치 2배. 1회용.",
        "icon": "🚀",
        "slot": "consumable",
        "rarity": "rare",
        "hp_bonus": 0,
        "mp_bonus": 0,
        "speed_bonus": 0,
        "luck_bonus": 0,
        "exp_multiplier": 2.0,
        "unlock_condition": None,
        "price": 500,
    },
    {
        "code": "revival_token",
        "name": "부활권",
        "description": "연속 출근 스트릭이 끊겨도 1회 복구.",
        "icon": "💖",
        "slot": "consumable",
        "rarity": "epic",
        "hp_bonus": 0,
        "mp_bonus": 0,
        "speed_bonus": 0,
        "luck_bonus": 0,
        "exp_multiplier": 1.0,
        "unlock_condition": None,
        "price": 1000,
    },
]
