"""캐릭터 스킬 시스템"""

SKILL_DEFINITIONS = [
    # === 인턴 스킬 ===
    {
        "code": "dash",
        "name": "환승 대시",
        "description": "환승 시 스피드 +50%. 지각 위기 탈출용.",
        "icon": "💨",
        "job_class": "intern",
        "level_required": 1,
        "cooldown_hours": 24,
        "effect": {"speed_boost": 50, "duration_minutes": 5},
    },
    {
        "code": "invisible",
        "name": "존재감 지우기",
        "description": "상사 눈에 안 띄게 출근. HP 페널티 50% 감소.",
        "icon": "👻",
        "job_class": "intern",
        "level_required": 3,
        "cooldown_hours": 48,
        "effect": {"hp_penalty_reduction": 50},
    },
    # === 사원 스킬 ===
    {
        "code": "coffee_boost",
        "name": "커피 부스트",
        "description": "아메리카노의 힘. 경험치 30% 추가 획득.",
        "icon": "☕",
        "job_class": "staff",
        "level_required": 10,
        "cooldown_hours": 24,
        "effect": {"exp_boost": 30},
    },
    {
        "code": "seat_finder",
        "name": "빈자리 감지",
        "description": "지하철 빈자리를 본능적으로 찾아냄. HP +20 회복.",
        "icon": "🪑",
        "job_class": "staff",
        "level_required": 15,
        "cooldown_hours": 12,
        "effect": {"hp_recovery": 20},
    },
    # === 대리 스킬 ===
    {
        "code": "time_warp",
        "name": "시간 왜곡",
        "description": "체감 통근 시간 감소. 경험치는 실제 시간 기준.",
        "icon": "⏳",
        "job_class": "senior",
        "level_required": 25,
        "cooldown_hours": 72,
        "effect": {"exp_boost": 50},
    },
    {
        "code": "crowd_split",
        "name": "인파 가르기",
        "description": "모세처럼 출근길 인파를 가른다. 스피드 2배.",
        "icon": "🌊",
        "job_class": "senior",
        "level_required": 30,
        "cooldown_hours": 48,
        "effect": {"speed_boost": 100, "duration_minutes": 10},
    },
    # === 과장 스킬 ===
    {
        "code": "taxi_call",
        "name": "택시 소환",
        "description": "비상시 택시 소환. HP 페널티 완전 무효화.",
        "icon": "🚕",
        "job_class": "manager",
        "level_required": 45,
        "cooldown_hours": 168,
        "effect": {"hp_penalty_reduction": 100},
    },
    {
        "code": "aura_of_calm",
        "name": "평정의 오라",
        "description": "주변 승객의 짜증을 흡수. 길드원 전체 MP +10.",
        "icon": "🧘",
        "job_class": "manager",
        "level_required": 50,
        "cooldown_hours": 48,
        "effect": {"guild_mp_boost": 10},
    },
    # === 임원 스킬 ===
    {
        "code": "telecommute",
        "name": "재택 선언",
        "description": "오늘은 재택. 출근 안 해도 경험치 절반 획득.",
        "icon": "🏠",
        "job_class": "director",
        "level_required": 70,
        "cooldown_hours": 168,
        "effect": {"remote_exp_ratio": 50},
    },
    # === 회장 스킬 ===
    {
        "code": "driver_summon",
        "name": "기사님 호출",
        "description": "전용 기사 소환. 보스 자동 클리어.",
        "icon": "🚗",
        "job_class": "executive",
        "level_required": 100,
        "cooldown_hours": 336,
        "effect": {"auto_boss_clear": True},
    },
    # === 전설 스킬 ===
    {
        "code": "time_lord",
        "name": "시간의 군주",
        "description": "출퇴근 경험치 3배. 전설의 힘.",
        "icon": "⚡",
        "job_class": "legend",
        "level_required": 150,
        "cooldown_hours": 720,
        "effect": {"exp_multiplier": 3.0},
    },
]
